from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.country_code_metadata_item import CountryCodeMetadataItem
from openapi_models.models.pagination import Pagination
from openapi_models import util

from openapi_models.models.country_code_metadata_item import (
    CountryCodeMetadataItem,
)  # noqa: E501
from openapi_models.models.pagination import Pagination  # noqa: E501


class CountryCodeMetadataListResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """CountryCodeMetadataListResponseBody - a model defined in OpenAPI

        :param data: The data of this CountryCodeMetadataListResponseBody.  # noqa: E501
        :type data: List[CountryCodeMetadataItem]
        :param pagination: The pagination of this CountryCodeMetadataListResponseBody.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            "data": List[CountryCodeMetadataItem],
            "pagination": Pagination,
        }

        self.attribute_map = {"data": "data", "pagination": "pagination"}

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> "CountryCodeMetadataListResponseBody":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CountryCodeMetadataListResponseBody of this CountryCodeMetadataListResponseBody.  # noqa: E501
        :rtype: CountryCodeMetadataListResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[CountryCodeMetadataItem]:
        """Gets the data of this CountryCodeMetadataListResponseBody.


        :return: The data of this CountryCodeMetadataListResponseBody.
        :rtype: List[CountryCodeMetadataItem]
        """
        return self._data

    @data.setter
    def data(self, data: List[CountryCodeMetadataItem]):
        """Sets the data of this CountryCodeMetadataListResponseBody.


        :param data: The data of this CountryCodeMetadataListResponseBody.
        :type data: List[CountryCodeMetadataItem]
        """
        if data is None:
            raise ValueError(
                "Invalid value for `data`, must not be `None`"
            )  # noqa: E501
        if data is not None and len(data) > 500:
            raise ValueError(
                "Invalid value for `data`, number of items must be less than or equal to `500`"
            )  # noqa: E501
        if data is not None and len(data) < 0:
            raise ValueError(
                "Invalid value for `data`, number of items must be greater than or equal to `0`"
            )  # noqa: E501

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this CountryCodeMetadataListResponseBody.


        :return: The pagination of this CountryCodeMetadataListResponseBody.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this CountryCodeMetadataListResponseBody.


        :param pagination: The pagination of this CountryCodeMetadataListResponseBody.
        :type pagination: Pagination
        """
        if pagination is None:
            raise ValueError(
                "Invalid value for `pagination`, must not be `None`"
            )  # noqa: E501

        self._pagination = pagination
