from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
import re
from openapi_models import util

import re  # noqa: E501


class Country(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, wikidata_id=None, name=None):  # noqa: E501
        """Country - a model defined in OpenAPI

        :param wikidata_id: The wikidata_id of this Country.  # noqa: E501
        :type wikidata_id: str
        :param name: The name of this Country.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {"wikidata_id": str, "name": str}

        self.attribute_map = {"wikidata_id": "wikidataId", "name": "name"}

        self._wikidata_id = wikidata_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> "Country":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wikidata_id(self) -> str:
        """Gets the wikidata_id of this Country.


        :return: The wikidata_id of this Country.
        :rtype: str
        """
        return self._wikidata_id

    @wikidata_id.setter
    def wikidata_id(self, wikidata_id: str):
        """Sets the wikidata_id of this Country.


        :param wikidata_id: The wikidata_id of this Country.
        :type wikidata_id: str
        """
        if wikidata_id is None:
            raise ValueError(
                "Invalid value for `wikidata_id`, must not be `None`"
            )  # noqa: E501

        self._wikidata_id = wikidata_id

    @property
    def name(self) -> str:
        """Gets the name of this Country.


        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Country.


        :param name: The name of this Country.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501
        if name is not None and len(name) > 120:
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `120`"
            )  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if name is not None and not re.search(r"^.*\S.*$", name):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._name = name
