from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
import re
from openapi_models import util

import re  # noqa: E501


class CountryCodeMetadataItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, name=None):  # noqa: E501
        """CountryCodeMetadataItem - a model defined in OpenAPI

        :param code: The code of this CountryCodeMetadataItem.  # noqa: E501
        :type code: str
        :param name: The name of this CountryCodeMetadataItem.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {"code": str, "name": str}

        self.attribute_map = {"code": "code", "name": "name"}

        self._code = code
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> "CountryCodeMetadataItem":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CountryCodeMetadataItem of this CountryCodeMetadataItem.  # noqa: E501
        :rtype: CountryCodeMetadataItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this CountryCodeMetadataItem.

        ISO 3166-1 alpha-3 country code (3 uppercase letters).  # noqa: E501

        :return: The code of this CountryCodeMetadataItem.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this CountryCodeMetadataItem.

        ISO 3166-1 alpha-3 country code (3 uppercase letters).  # noqa: E501

        :param code: The code of this CountryCodeMetadataItem.
        :type code: str
        """
        if code is None:
            raise ValueError(
                "Invalid value for `code`, must not be `None`"
            )  # noqa: E501
        if code is not None and len(code) > 3:
            raise ValueError(
                "Invalid value for `code`, length must be less than or equal to `3`"
            )  # noqa: E501
        if code is not None and len(code) < 3:
            raise ValueError(
                "Invalid value for `code`, length must be greater than or equal to `3`"
            )  # noqa: E501
        if code is not None and not re.search(r"^[A-Z]{3}$", code):  # noqa: E501
            raise ValueError(
                "Invalid value for `code`, must be a follow pattern or equal to `/^[A-Z]{3}$/`"
            )  # noqa: E501

        self._code = code

    @property
    def name(self) -> str:
        """Gets the name of this CountryCodeMetadataItem.


        :return: The name of this CountryCodeMetadataItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CountryCodeMetadataItem.


        :param name: The name of this CountryCodeMetadataItem.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501
        if name is not None and len(name) > 120:
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `120`"
            )  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if name is not None and not re.search(r"^.*\S.*$", name):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._name = name
