from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.event_type_metadata_item import EventTypeMetadataItem
from openapi_models import util

from openapi_models.models.event_type_metadata_item import EventTypeMetadataItem  # noqa: E501

class EventTypeMetadataListResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """EventTypeMetadataListResponseBody - a model defined in OpenAPI

        :param data: The data of this EventTypeMetadataListResponseBody.  # noqa: E501
        :type data: List[EventTypeMetadataItem]
        """
        self.openapi_types = {
            'data': List[EventTypeMetadataItem]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'EventTypeMetadataListResponseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventTypeMetadataListResponseBody of this EventTypeMetadataListResponseBody.  # noqa: E501
        :rtype: EventTypeMetadataListResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[EventTypeMetadataItem]:
        """Gets the data of this EventTypeMetadataListResponseBody.


        :return: The data of this EventTypeMetadataListResponseBody.
        :rtype: List[EventTypeMetadataItem]
        """
        return self._data

    @data.setter
    def data(self, data: List[EventTypeMetadataItem]):
        """Sets the data of this EventTypeMetadataListResponseBody.


        :param data: The data of this EventTypeMetadataListResponseBody.
        :type data: List[EventTypeMetadataItem]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501
        if data is not None and len(data) > 1000:
            raise ValueError("Invalid value for `data`, number of items must be less than or equal to `1000`")  # noqa: E501
        if data is not None and len(data) < 0:
            raise ValueError("Invalid value for `data`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._data = data
