from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models import util


class EventType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GEOPOLITICAL_GROUP = 'GEOPOLITICAL_GROUP'
    INTERNATIONAL_ORGANISATION = 'INTERNATIONAL_ORGANISATION'
    MILITARY_ALLIANCE = 'MILITARY_ALLIANCE'
    MULTINATIONAL_MILITARY_COALITION = 'MULTINATIONAL_MILITARY_COALITION'
    POLITICAL_CONFERENCE = 'POLITICAL_CONFERENCE'
    POLITICAL_CRISIS = 'POLITICAL_CRISIS'
    POLITICAL_MURDER = 'POLITICAL_MURDER'
    SOURCE_OF_INTERNATIONAL_LAW = 'SOURCE_OF_INTERNATIONAL_LAW'
    SUPRANATIONAL_UNION = 'SUPRANATIONAL_UNION'
    WARFARE_AND_ARMED_CONFLICTS = 'WARFARE_AND_ARMED_CONFLICTS'
    def __init__(self):  # noqa: E501
        """EventType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EventType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventType of this EventType.  # noqa: E501
        :rtype: EventType
        """
        return util.deserialize_model(dikt, cls)
