from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.event_event_type import EventEventType
import re
from openapi_models import util

from openapi_models.models.event_event_type import EventEventType  # noqa: E501
import re  # noqa: E501


class EventTypeMetadataItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, name=None, description=None):  # noqa: E501
        """EventTypeMetadataItem - a model defined in OpenAPI

        :param code: The code of this EventTypeMetadataItem.  # noqa: E501
        :type code: EventEventType
        :param name: The name of this EventTypeMetadataItem.  # noqa: E501
        :type name: str
        :param description: The description of this EventTypeMetadataItem.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {"code": EventEventType, "name": str, "description": str}

        self.attribute_map = {
            "code": "code",
            "name": "name",
            "description": "description",
        }

        self._code = code
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> "EventTypeMetadataItem":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventTypeMetadataItem of this EventTypeMetadataItem.  # noqa: E501
        :rtype: EventTypeMetadataItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> EventEventType:
        """Gets the code of this EventTypeMetadataItem.


        :return: The code of this EventTypeMetadataItem.
        :rtype: EventEventType
        """
        return self._code

    @code.setter
    def code(self, code: EventEventType):
        """Sets the code of this EventTypeMetadataItem.


        :param code: The code of this EventTypeMetadataItem.
        :type code: EventEventType
        """
        if code is None:
            raise ValueError(
                "Invalid value for `code`, must not be `None`"
            )  # noqa: E501

        self._code = code

    @property
    def name(self) -> str:
        """Gets the name of this EventTypeMetadataItem.


        :return: The name of this EventTypeMetadataItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EventTypeMetadataItem.


        :param name: The name of this EventTypeMetadataItem.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501
        if name is not None and len(name) > 120:
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `120`"
            )  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if name is not None and not re.search(r"^.*\S.*$", name):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this EventTypeMetadataItem.


        :return: The description of this EventTypeMetadataItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this EventTypeMetadataItem.


        :param description: The description of this EventTypeMetadataItem.
        :type description: str
        """
        if description is None:
            raise ValueError(
                "Invalid value for `description`, must not be `None`"
            )  # noqa: E501
        if description is not None and len(description) > 500:
            raise ValueError(
                "Invalid value for `description`, length must be less than or equal to `500`"
            )  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError(
                "Invalid value for `description`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if description is not None and not re.search(
            r"^.*\S.*$", description
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `description`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._description = description
