from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models import util


class EventEventTimeStateRelativeToNow(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PAST = "PAST"
    ONGOING = "ONGOING"
    FUTURE = "FUTURE"

    def __init__(self):  # noqa: E501
        """EventEventTimeStateRelativeToNow - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "EventEventTimeStateRelativeToNow":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The event_EventTimeStateRelativeToNow of this EventEventTimeStateRelativeToNow.  # noqa: E501
        :rtype: EventEventTimeStateRelativeToNow
        """
        return util.deserialize_model(dikt, cls)
