from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.country import Country
from openapi_models.models.event_event_time_state_relative_to_now import (
    EventEventTimeStateRelativeToNow,
)
from openapi_models.models.event_event_type import EventEventType
from openapi_models.models.location import Location
from openapi_models.models.region import Region
import re
from openapi_models import util

from openapi_models.models.country import Country  # noqa: E501
from openapi_models.models.event_event_time_state_relative_to_now import (
    EventEventTimeStateRelativeToNow,
)  # noqa: E501
from openapi_models.models.event_event_type import EventEventType  # noqa: E501
from openapi_models.models.location import Location  # noqa: E501
from openapi_models.models.region import Region  # noqa: E501
import re  # noqa: E501


class EventEvent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        type=None,
        wikidata_id=None,
        wikidata_url=None,
        name=None,
        description=None,
        wikipedia_url=None,
        image_url=None,
        regions=None,
        countries=None,
        locations=None,
        time_state_relative_to_now=None,
        start_date_time=None,
        end_date_time=None,
    ):  # noqa: E501
        """EventEvent - a model defined in OpenAPI

        :param type: The type of this EventEvent.  # noqa: E501
        :type type: EventEventType
        :param wikidata_id: The wikidata_id of this EventEvent.  # noqa: E501
        :type wikidata_id: str
        :param wikidata_url: The wikidata_url of this EventEvent.  # noqa: E501
        :type wikidata_url: str
        :param name: The name of this EventEvent.  # noqa: E501
        :type name: str
        :param description: The description of this EventEvent.  # noqa: E501
        :type description: str
        :param wikipedia_url: The wikipedia_url of this EventEvent.  # noqa: E501
        :type wikipedia_url: str
        :param image_url: The image_url of this EventEvent.  # noqa: E501
        :type image_url: str
        :param regions: The regions of this EventEvent.  # noqa: E501
        :type regions: List[Region]
        :param countries: The countries of this EventEvent.  # noqa: E501
        :type countries: List[Country]
        :param locations: The locations of this EventEvent.  # noqa: E501
        :type locations: List[Location]
        :param time_state_relative_to_now: The time_state_relative_to_now of this EventEvent.  # noqa: E501
        :type time_state_relative_to_now: EventEventTimeStateRelativeToNow
        :param start_date_time: The start_date_time of this EventEvent.  # noqa: E501
        :type start_date_time: str
        :param end_date_time: The end_date_time of this EventEvent.  # noqa: E501
        :type end_date_time: str
        """
        self.openapi_types = {
            "type": EventEventType,
            "wikidata_id": str,
            "wikidata_url": str,
            "name": str,
            "description": str,
            "wikipedia_url": str,
            "image_url": str,
            "regions": List[Region],
            "countries": List[Country],
            "locations": List[Location],
            "time_state_relative_to_now": EventEventTimeStateRelativeToNow,
            "start_date_time": str,
            "end_date_time": str,
        }

        self.attribute_map = {
            "type": "type",
            "wikidata_id": "wikidataId",
            "wikidata_url": "wikidataUrl",
            "name": "name",
            "description": "description",
            "wikipedia_url": "wikipediaUrl",
            "image_url": "imageUrl",
            "regions": "regions",
            "countries": "countries",
            "locations": "locations",
            "time_state_relative_to_now": "timeStateRelativeToNow",
            "start_date_time": "startDateTime",
            "end_date_time": "endDateTime",
        }

        self._type = type
        self._wikidata_id = wikidata_id
        self._wikidata_url = wikidata_url
        self._name = name
        self._description = description
        self._wikipedia_url = wikipedia_url
        self._image_url = image_url
        self._regions = regions
        self._countries = countries
        self._locations = locations
        self._time_state_relative_to_now = time_state_relative_to_now
        self._start_date_time = start_date_time
        self._end_date_time = end_date_time

    @classmethod
    def from_dict(cls, dikt) -> "EventEvent":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The event_Event of this EventEvent.  # noqa: E501
        :rtype: EventEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> EventEventType:
        """Gets the type of this EventEvent.


        :return: The type of this EventEvent.
        :rtype: EventEventType
        """
        return self._type

    @type.setter
    def type(self, type: EventEventType):
        """Sets the type of this EventEvent.


        :param type: The type of this EventEvent.
        :type type: EventEventType
        """
        if type is None:
            raise ValueError(
                "Invalid value for `type`, must not be `None`"
            )  # noqa: E501

        self._type = type

    @property
    def wikidata_id(self) -> str:
        """Gets the wikidata_id of this EventEvent.

        Wikidata entity ID (e.g., Q178810).  # noqa: E501

        :return: The wikidata_id of this EventEvent.
        :rtype: str
        """
        return self._wikidata_id

    @wikidata_id.setter
    def wikidata_id(self, wikidata_id: str):
        """Sets the wikidata_id of this EventEvent.

        Wikidata entity ID (e.g., Q178810).  # noqa: E501

        :param wikidata_id: The wikidata_id of this EventEvent.
        :type wikidata_id: str
        """
        if wikidata_id is None:
            raise ValueError(
                "Invalid value for `wikidata_id`, must not be `None`"
            )  # noqa: E501
        if wikidata_id is not None and len(wikidata_id) > 32:
            raise ValueError(
                "Invalid value for `wikidata_id`, length must be less than or equal to `32`"
            )  # noqa: E501
        if wikidata_id is not None and len(wikidata_id) < 2:
            raise ValueError(
                "Invalid value for `wikidata_id`, length must be greater than or equal to `2`"
            )  # noqa: E501
        if wikidata_id is not None and not re.search(
            r"^Q[1-9][0-9]*$", wikidata_id
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `wikidata_id`, must be a follow pattern or equal to `/^Q[1-9][0-9]*$/`"
            )  # noqa: E501

        self._wikidata_id = wikidata_id

    @property
    def wikidata_url(self) -> str:
        """Gets the wikidata_url of this EventEvent.

        URL of the corresponding Wikidata item.  # noqa: E501

        :return: The wikidata_url of this EventEvent.
        :rtype: str
        """
        return self._wikidata_url

    @wikidata_url.setter
    def wikidata_url(self, wikidata_url: str):
        """Sets the wikidata_url of this EventEvent.

        URL of the corresponding Wikidata item.  # noqa: E501

        :param wikidata_url: The wikidata_url of this EventEvent.
        :type wikidata_url: str
        """
        if wikidata_url is None:
            raise ValueError(
                "Invalid value for `wikidata_url`, must not be `None`"
            )  # noqa: E501
        if wikidata_url is not None and len(wikidata_url) > 120:
            raise ValueError(
                "Invalid value for `wikidata_url`, length must be less than or equal to `120`"
            )  # noqa: E501
        if wikidata_url is not None and len(wikidata_url) < 27:
            raise ValueError(
                "Invalid value for `wikidata_url`, length must be greater than or equal to `27`"
            )  # noqa: E501
        if wikidata_url is not None and not re.search(
            r"^https?:\/\/(www\.)?wikidata\.org\/wiki\/Q[1-9][0-9]*$", wikidata_url
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `wikidata_url`, must be a follow pattern or equal to `/^https?:\/\/(www\.)?wikidata\.org\/wiki\/Q[1-9][0-9]*$/`"
            )  # noqa: E501

        self._wikidata_url = wikidata_url

    @property
    def name(self) -> str:
        """Gets the name of this EventEvent.

        Name of a historical political Event.  # noqa: E501

        :return: The name of this EventEvent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EventEvent.

        Name of a historical political Event.  # noqa: E501

        :param name: The name of this EventEvent.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501
        if name is not None and len(name) > 200:
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `200`"
            )  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if name is not None and not re.search(r"^.*\S.*$", name):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this EventEvent.

        Detailed information about a historical political Event.  # noqa: E501

        :return: The description of this EventEvent.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this EventEvent.

        Detailed information about a historical political Event.  # noqa: E501

        :param description: The description of this EventEvent.
        :type description: str
        """
        if description is not None and len(description) > 5000:
            raise ValueError(
                "Invalid value for `description`, length must be less than or equal to `5000`"
            )  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError(
                "Invalid value for `description`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if description is not None and not re.search(
            r"^.*\S.*$", description
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `description`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._description = description

    @property
    def wikipedia_url(self) -> str:
        """Gets the wikipedia_url of this EventEvent.

        URL of the corresponding Wikipedia article.  # noqa: E501

        :return: The wikipedia_url of this EventEvent.
        :rtype: str
        """
        return self._wikipedia_url

    @wikipedia_url.setter
    def wikipedia_url(self, wikipedia_url: str):
        """Sets the wikipedia_url of this EventEvent.

        URL of the corresponding Wikipedia article.  # noqa: E501

        :param wikipedia_url: The wikipedia_url of this EventEvent.
        :type wikipedia_url: str
        """
        if wikipedia_url is not None and len(wikipedia_url) > 300:
            raise ValueError(
                "Invalid value for `wikipedia_url`, length must be less than or equal to `300`"
            )  # noqa: E501
        if wikipedia_url is not None and len(wikipedia_url) < 24:
            raise ValueError(
                "Invalid value for `wikipedia_url`, length must be greater than or equal to `24`"
            )  # noqa: E501
        if wikipedia_url is not None and not re.search(
            r"^https?:\/\/([a-z]{2,3}\.)?wikipedia\.org\/wiki\/.+$", wikipedia_url
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `wikipedia_url`, must be a follow pattern or equal to `/^https?:\/\/([a-z]{2,3}\.)?wikipedia\.org\/wiki\/.+$/`"
            )  # noqa: E501

        self._wikipedia_url = wikipedia_url

    @property
    def image_url(self) -> str:
        """Gets the image_url of this EventEvent.

        URL of an image representing the event.  # noqa: E501

        :return: The image_url of this EventEvent.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this EventEvent.

        URL of an image representing the event.  # noqa: E501

        :param image_url: The image_url of this EventEvent.
        :type image_url: str
        """
        if image_url is not None and len(image_url) > 500:
            raise ValueError(
                "Invalid value for `image_url`, length must be less than or equal to `500`"
            )  # noqa: E501
        if image_url is not None and len(image_url) < 12:
            raise ValueError(
                "Invalid value for `image_url`, length must be greater than or equal to `12`"
            )  # noqa: E501
        if image_url is not None and not re.search(
            r"^https?:\/\/.+$", image_url
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `image_url`, must be a follow pattern or equal to `/^https?:\/\/.+$/`"
            )  # noqa: E501

        self._image_url = image_url

    @property
    def regions(self) -> List[Region]:
        """Gets the regions of this EventEvent.

        List of World Regions to filter Events.  # noqa: E501

        :return: The regions of this EventEvent.
        :rtype: List[Region]
        """
        return self._regions

    @regions.setter
    def regions(self, regions: List[Region]):
        """Sets the regions of this EventEvent.

        List of World Regions to filter Events.  # noqa: E501

        :param regions: The regions of this EventEvent.
        :type regions: List[Region]
        """
        if regions is not None and len(regions) > 10:
            raise ValueError(
                "Invalid value for `regions`, number of items must be less than or equal to `10`"
            )  # noqa: E501
        if regions is not None and len(regions) < 0:
            raise ValueError(
                "Invalid value for `regions`, number of items must be greater than or equal to `0`"
            )  # noqa: E501

        self._regions = regions

    @property
    def countries(self) -> List[Country]:
        """Gets the countries of this EventEvent.

        List of Countries related to the Event.  # noqa: E501

        :return: The countries of this EventEvent.
        :rtype: List[Country]
        """
        return self._countries

    @countries.setter
    def countries(self, countries: List[Country]):
        """Sets the countries of this EventEvent.

        List of Countries related to the Event.  # noqa: E501

        :param countries: The countries of this EventEvent.
        :type countries: List[Country]
        """
        if countries is not None and len(countries) > 200:
            raise ValueError(
                "Invalid value for `countries`, number of items must be less than or equal to `200`"
            )  # noqa: E501
        if countries is not None and len(countries) < 0:
            raise ValueError(
                "Invalid value for `countries`, number of items must be greater than or equal to `0`"
            )  # noqa: E501

        self._countries = countries

    @property
    def locations(self) -> List[Location]:
        """Gets the locations of this EventEvent.

        List of Locations related to the Event.  # noqa: E501

        :return: The locations of this EventEvent.
        :rtype: List[Location]
        """
        return self._locations

    @locations.setter
    def locations(self, locations: List[Location]):
        """Sets the locations of this EventEvent.

        List of Locations related to the Event.  # noqa: E501

        :param locations: The locations of this EventEvent.
        :type locations: List[Location]
        """
        if locations is not None and len(locations) > 200:
            raise ValueError(
                "Invalid value for `locations`, number of items must be less than or equal to `200`"
            )  # noqa: E501
        if locations is not None and len(locations) < 0:
            raise ValueError(
                "Invalid value for `locations`, number of items must be greater than or equal to `0`"
            )  # noqa: E501

        self._locations = locations

    @property
    def time_state_relative_to_now(self) -> EventEventTimeStateRelativeToNow:
        """Gets the time_state_relative_to_now of this EventEvent.


        :return: The time_state_relative_to_now of this EventEvent.
        :rtype: EventEventTimeStateRelativeToNow
        """
        return self._time_state_relative_to_now

    @time_state_relative_to_now.setter
    def time_state_relative_to_now(
        self, time_state_relative_to_now: EventEventTimeStateRelativeToNow
    ):
        """Sets the time_state_relative_to_now of this EventEvent.


        :param time_state_relative_to_now: The time_state_relative_to_now of this EventEvent.
        :type time_state_relative_to_now: EventEventTimeStateRelativeToNow
        """
        if time_state_relative_to_now is None:
            raise ValueError(
                "Invalid value for `time_state_relative_to_now`, must not be `None`"
            )  # noqa: E501

        self._time_state_relative_to_now = time_state_relative_to_now

    @property
    def start_date_time(self) -> str:
        """Gets the start_date_time of this EventEvent.

        Event timestamp in UTC using ISO 8601 date-time format.  # noqa: E501

        :return: The start_date_time of this EventEvent.
        :rtype: str
        """
        return self._start_date_time

    @start_date_time.setter
    def start_date_time(self, start_date_time: str):
        """Sets the start_date_time of this EventEvent.

        Event timestamp in UTC using ISO 8601 date-time format.  # noqa: E501

        :param start_date_time: The start_date_time of this EventEvent.
        :type start_date_time: str
        """
        if start_date_time is None:
            raise ValueError(
                "Invalid value for `start_date_time`, must not be `None`"
            )  # noqa: E501
        if start_date_time is not None and len(start_date_time) > 35:
            raise ValueError(
                "Invalid value for `start_date_time`, length must be less than or equal to `35`"
            )  # noqa: E501
        if start_date_time is not None and len(start_date_time) < 20:
            raise ValueError(
                "Invalid value for `start_date_time`, length must be greater than or equal to `20`"
            )  # noqa: E501
        if start_date_time is not None and not re.search(
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$", start_date_time
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `start_date_time`, must be a follow pattern or equal to `/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/`"
            )  # noqa: E501

        self._start_date_time = start_date_time

    @property
    def end_date_time(self) -> str:
        """Gets the end_date_time of this EventEvent.

        Event timestamp in UTC using ISO 8601 date-time format.  # noqa: E501

        :return: The end_date_time of this EventEvent.
        :rtype: str
        """
        return self._end_date_time

    @end_date_time.setter
    def end_date_time(self, end_date_time: str):
        """Sets the end_date_time of this EventEvent.

        Event timestamp in UTC using ISO 8601 date-time format.  # noqa: E501

        :param end_date_time: The end_date_time of this EventEvent.
        :type end_date_time: str
        """
        if end_date_time is not None and len(end_date_time) > 35:
            raise ValueError(
                "Invalid value for `end_date_time`, length must be less than or equal to `35`"
            )  # noqa: E501
        if end_date_time is not None and len(end_date_time) < 20:
            raise ValueError(
                "Invalid value for `end_date_time`, length must be greater than or equal to `20`"
            )  # noqa: E501
        if end_date_time is not None and not re.search(
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$", end_date_time
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `end_date_time`, must be a follow pattern or equal to `/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/`"
            )  # noqa: E501

        self._end_date_time = end_date_time
