from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models import util


class Event(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        type=None,
        wikidata_id=None,
        name=None,
        time_state_relative_to_now=None,
        start_time=None,
    ):  # noqa: E501
        """Event - a model defined in OpenAPI

        :param type: The type of this Event.  # noqa: E501
        :type type: str
        :param wikidata_id: The wikidata_id of this Event.  # noqa: E501
        :type wikidata_id: str
        :param name: The name of this Event.  # noqa: E501
        :type name: str
        :param time_state_relative_to_now: The time_state_relative_to_now of this Event.  # noqa: E501
        :type time_state_relative_to_now: str
        :param start_time: The start_time of this Event.  # noqa: E501
        :type start_time: str
        """
        self.openapi_types = {
            "type": str,
            "wikidata_id": str,
            "name": str,
            "time_state_relative_to_now": str,
            "start_time": str,
        }

        self.attribute_map = {
            "type": "type",
            "wikidata_id": "wikidataId",
            "name": "name",
            "time_state_relative_to_now": "timeStateRelativeToNow",
            "start_time": "startTime",
        }

        self._type = type
        self._wikidata_id = wikidata_id
        self._name = name
        self._time_state_relative_to_now = time_state_relative_to_now
        self._start_time = start_time

    @classmethod
    def from_dict(cls, dikt) -> "Event":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Event of this Event.  # noqa: E501
        :rtype: Event
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Event.


        :return: The type of this Event.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Event.


        :param type: The type of this Event.
        :type type: str
        """
        if type is None:
            raise ValueError(
                "Invalid value for `type`, must not be `None`"
            )  # noqa: E501

        self._type = type

    @property
    def wikidata_id(self) -> str:
        """Gets the wikidata_id of this Event.

        Record ID of a data item in https://www.wikidata.org.  # noqa: E501

        :return: The wikidata_id of this Event.
        :rtype: str
        """
        return self._wikidata_id

    @wikidata_id.setter
    def wikidata_id(self, wikidata_id: str):
        """Sets the wikidata_id of this Event.

        Record ID of a data item in https://www.wikidata.org.  # noqa: E501

        :param wikidata_id: The wikidata_id of this Event.
        :type wikidata_id: str
        """
        if wikidata_id is None:
            raise ValueError(
                "Invalid value for `wikidata_id`, must not be `None`"
            )  # noqa: E501

        self._wikidata_id = wikidata_id

    @property
    def name(self) -> str:
        """Gets the name of this Event.

        Name of a historical political Event.  # noqa: E501

        :return: The name of this Event.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Event.

        Name of a historical political Event.  # noqa: E501

        :param name: The name of this Event.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def time_state_relative_to_now(self) -> str:
        """Gets the time_state_relative_to_now of this Event.


        :return: The time_state_relative_to_now of this Event.
        :rtype: str
        """
        return self._time_state_relative_to_now

    @time_state_relative_to_now.setter
    def time_state_relative_to_now(self, time_state_relative_to_now: str):
        """Sets the time_state_relative_to_now of this Event.


        :param time_state_relative_to_now: The time_state_relative_to_now of this Event.
        :type time_state_relative_to_now: str
        """

        self._time_state_relative_to_now = time_state_relative_to_now

    @property
    def start_time(self) -> str:
        """Gets the start_time of this Event.


        :return: The start_time of this Event.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """Sets the start_time of this Event.


        :param start_time: The start_time of this Event.
        :type start_time: str
        """
        if start_time is None:
            raise ValueError(
                "Invalid value for `start_time`, must not be `None`"
            )  # noqa: E501

        self._start_time = start_time
