from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.event import Event
from openapi_models.models.pagination import Pagination
from openapi_models import util

from openapi_models.models.event import Event  # noqa: E501
from openapi_models.models.pagination import Pagination  # noqa: E501

class EventListResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """EventListResponseBody - a model defined in OpenAPI

        :param data: The data of this EventListResponseBody.  # noqa: E501
        :type data: List[Event]
        :param pagination: The pagination of this EventListResponseBody.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'data': List[Event],
            'pagination': Pagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'EventListResponseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventListResponseBody of this EventListResponseBody.  # noqa: E501
        :rtype: EventListResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Event]:
        """Gets the data of this EventListResponseBody.


        :return: The data of this EventListResponseBody.
        :rtype: List[Event]
        """
        return self._data

    @data.setter
    def data(self, data: List[Event]):
        """Sets the data of this EventListResponseBody.


        :param data: The data of this EventListResponseBody.
        :type data: List[Event]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501
        if data is not None and len(data) > 1000:
            raise ValueError("Invalid value for `data`, number of items must be less than or equal to `1000`")  # noqa: E501
        if data is not None and len(data) < 0:
            raise ValueError("Invalid value for `data`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this EventListResponseBody.


        :return: The pagination of this EventListResponseBody.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this EventListResponseBody.


        :param pagination: The pagination of this EventListResponseBody.
        :type pagination: Pagination
        """
        if pagination is None:
            raise ValueError("Invalid value for `pagination`, must not be `None`")  # noqa: E501

        self._pagination = pagination
