from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
import re
from openapi_models import util

import re  # noqa: E501


class Location(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, wikidata_id=None, name=None, coordinate=None):  # noqa: E501
        """Location - a model defined in OpenAPI

        :param wikidata_id: The wikidata_id of this Location.  # noqa: E501
        :type wikidata_id: str
        :param name: The name of this Location.  # noqa: E501
        :type name: str
        :param coordinate: The coordinate of this Location.  # noqa: E501
        :type coordinate: str
        """
        self.openapi_types = {"wikidata_id": str, "name": str, "coordinate": str}

        self.attribute_map = {
            "wikidata_id": "wikidataId",
            "name": "name",
            "coordinate": "coordinate",
        }

        self._wikidata_id = wikidata_id
        self._name = name
        self._coordinate = coordinate

    @classmethod
    def from_dict(cls, dikt) -> "Location":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Location of this Location.  # noqa: E501
        :rtype: Location
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wikidata_id(self) -> str:
        """Gets the wikidata_id of this Location.


        :return: The wikidata_id of this Location.
        :rtype: str
        """
        return self._wikidata_id

    @wikidata_id.setter
    def wikidata_id(self, wikidata_id: str):
        """Sets the wikidata_id of this Location.


        :param wikidata_id: The wikidata_id of this Location.
        :type wikidata_id: str
        """
        if wikidata_id is None:
            raise ValueError(
                "Invalid value for `wikidata_id`, must not be `None`"
            )  # noqa: E501

        self._wikidata_id = wikidata_id

    @property
    def name(self) -> str:
        """Gets the name of this Location.


        :return: The name of this Location.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Location.


        :param name: The name of this Location.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501
        if name is not None and len(name) > 120:
            raise ValueError(
                "Invalid value for `name`, length must be less than or equal to `120`"
            )  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError(
                "Invalid value for `name`, length must be greater than or equal to `1`"
            )  # noqa: E501
        if name is not None and not re.search(r"^.*\S.*$", name):  # noqa: E501
            raise ValueError(
                "Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`"
            )  # noqa: E501

        self._name = name

    @property
    def coordinate(self) -> str:
        """Gets the coordinate of this Location.


        :return: The coordinate of this Location.
        :rtype: str
        """
        return self._coordinate

    @coordinate.setter
    def coordinate(self, coordinate: str):
        """Sets the coordinate of this Location.


        :param coordinate: The coordinate of this Location.
        :type coordinate: str
        """
        if coordinate is None:
            raise ValueError(
                "Invalid value for `coordinate`, must not be `None`"
            )  # noqa: E501
        if coordinate is not None and len(coordinate) > 32:
            raise ValueError(
                "Invalid value for `coordinate`, length must be less than or equal to `32`"
            )  # noqa: E501
        if coordinate is not None and len(coordinate) < 7:
            raise ValueError(
                "Invalid value for `coordinate`, length must be greater than or equal to `7`"
            )  # noqa: E501
        if coordinate is not None and not re.search(
            r"^-?\d{1,2}\.\d+,-?\d{1,3}\.\d+$", coordinate
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `coordinate`, must be a follow pattern or equal to `/^-?\d{1,2}\.\d+,-?\d{1,3}\.\d+$/`"
            )  # noqa: E501

        self._coordinate = coordinate
