from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models import util


class Pagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, page_size=None, total_items=None, total_pages=None, has_next_page=None):  # noqa: E501
        """Pagination - a model defined in OpenAPI

        :param page: The page of this Pagination.  # noqa: E501
        :type page: int
        :param page_size: The page_size of this Pagination.  # noqa: E501
        :type page_size: int
        :param total_items: The total_items of this Pagination.  # noqa: E501
        :type total_items: int
        :param total_pages: The total_pages of this Pagination.  # noqa: E501
        :type total_pages: int
        :param has_next_page: The has_next_page of this Pagination.  # noqa: E501
        :type has_next_page: bool
        """
        self.openapi_types = {
            'page': int,
            'page_size': int,
            'total_items': int,
            'total_pages': int,
            'has_next_page': bool
        }

        self.attribute_map = {
            'page': 'page',
            'page_size': 'pageSize',
            'total_items': 'totalItems',
            'total_pages': 'totalPages',
            'has_next_page': 'hasNextPage'
        }

        self._page = page
        self._page_size = page_size
        self._total_items = total_items
        self._total_pages = total_pages
        self._has_next_page = has_next_page

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this Pagination.


        :return: The page of this Pagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this Pagination.


        :param page: The page of this Pagination.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501
        if page is not None and page < 1:  # noqa: E501
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page = page

    @property
    def page_size(self) -> int:
        """Gets the page_size of this Pagination.


        :return: The page_size of this Pagination.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this Pagination.


        :param page_size: The page_size of this Pagination.
        :type page_size: int
        """
        if page_size is None:
            raise ValueError("Invalid value for `page_size`, must not be `None`")  # noqa: E501
        if page_size is not None and page_size > 1000:  # noqa: E501
            raise ValueError("Invalid value for `page_size`, must be a value less than or equal to `1000`")  # noqa: E501
        if page_size is not None and page_size < 1:  # noqa: E501
            raise ValueError("Invalid value for `page_size`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page_size = page_size

    @property
    def total_items(self) -> int:
        """Gets the total_items of this Pagination.


        :return: The total_items of this Pagination.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items: int):
        """Sets the total_items of this Pagination.


        :param total_items: The total_items of this Pagination.
        :type total_items: int
        """
        if total_items is None:
            raise ValueError("Invalid value for `total_items`, must not be `None`")  # noqa: E501
        if total_items is not None and total_items < 0:  # noqa: E501
            raise ValueError("Invalid value for `total_items`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total_items = total_items

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this Pagination.


        :return: The total_pages of this Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this Pagination.


        :param total_pages: The total_pages of this Pagination.
        :type total_pages: int
        """
        if total_pages is None:
            raise ValueError("Invalid value for `total_pages`, must not be `None`")  # noqa: E501
        if total_pages is not None and total_pages < 0:  # noqa: E501
            raise ValueError("Invalid value for `total_pages`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total_pages = total_pages

    @property
    def has_next_page(self) -> bool:
        """Gets the has_next_page of this Pagination.


        :return: The has_next_page of this Pagination.
        :rtype: bool
        """
        return self._has_next_page

    @has_next_page.setter
    def has_next_page(self, has_next_page: bool):
        """Sets the has_next_page of this Pagination.


        :param has_next_page: The has_next_page of this Pagination.
        :type has_next_page: bool
        """
        if has_next_page is None:
            raise ValueError("Invalid value for `has_next_page`, must not be `None`")  # noqa: E501

        self._has_next_page = has_next_page
