from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.region_metadata_item import RegionMetadataItem
from openapi_models import util

from openapi_models.models.region_metadata_item import RegionMetadataItem  # noqa: E501


class RegionMetadataListResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """RegionMetadataListResponseBody - a model defined in OpenAPI

        :param data: The data of this RegionMetadataListResponseBody.  # noqa: E501
        :type data: List[RegionMetadataItem]
        """
        self.openapi_types = {"data": List[RegionMetadataItem]}

        self.attribute_map = {"data": "data"}

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> "RegionMetadataListResponseBody":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegionMetadataListResponseBody of this RegionMetadataListResponseBody.  # noqa: E501
        :rtype: RegionMetadataListResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[RegionMetadataItem]:
        """Gets the data of this RegionMetadataListResponseBody.


        :return: The data of this RegionMetadataListResponseBody.
        :rtype: List[RegionMetadataItem]
        """
        return self._data

    @data.setter
    def data(self, data: List[RegionMetadataItem]):
        """Sets the data of this RegionMetadataListResponseBody.


        :param data: The data of this RegionMetadataListResponseBody.
        :type data: List[RegionMetadataItem]
        """
        if data is None:
            raise ValueError(
                "Invalid value for `data`, must not be `None`"
            )  # noqa: E501
        if data is not None and len(data) > 50:
            raise ValueError(
                "Invalid value for `data`, number of items must be less than or equal to `50`"
            )  # noqa: E501
        if data is not None and len(data) < 0:
            raise ValueError(
                "Invalid value for `data`, number of items must be greater than or equal to `0`"
            )  # noqa: E501

        self._data = data
