from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models.models.region import Region
import re
from openapi_models import util

from openapi_models.models.region import Region  # noqa: E501
import re  # noqa: E501

class RegionMetadataItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, name=None, description=None, display_order=None, parent_code=None, aliases=None):  # noqa: E501
        """RegionMetadataItem - a model defined in OpenAPI

        :param code: The code of this RegionMetadataItem.  # noqa: E501
        :type code: Region
        :param name: The name of this RegionMetadataItem.  # noqa: E501
        :type name: str
        :param description: The description of this RegionMetadataItem.  # noqa: E501
        :type description: str
        :param display_order: The display_order of this RegionMetadataItem.  # noqa: E501
        :type display_order: int
        :param parent_code: The parent_code of this RegionMetadataItem.  # noqa: E501
        :type parent_code: str
        :param aliases: The aliases of this RegionMetadataItem.  # noqa: E501
        :type aliases: List[str]
        """
        self.openapi_types = {
            'code': Region,
            'name': str,
            'description': str,
            'display_order': int,
            'parent_code': str,
            'aliases': List[str]
        }

        self.attribute_map = {
            'code': 'code',
            'name': 'name',
            'description': 'description',
            'display_order': 'displayOrder',
            'parent_code': 'parentCode',
            'aliases': 'aliases'
        }

        self._code = code
        self._name = name
        self._description = description
        self._display_order = display_order
        self._parent_code = parent_code
        self._aliases = aliases

    @classmethod
    def from_dict(cls, dikt) -> 'RegionMetadataItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegionMetadataItem of this RegionMetadataItem.  # noqa: E501
        :rtype: RegionMetadataItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> Region:
        """Gets the code of this RegionMetadataItem.


        :return: The code of this RegionMetadataItem.
        :rtype: Region
        """
        return self._code

    @code.setter
    def code(self, code: Region):
        """Sets the code of this RegionMetadataItem.


        :param code: The code of this RegionMetadataItem.
        :type code: Region
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def name(self) -> str:
        """Gets the name of this RegionMetadataItem.


        :return: The name of this RegionMetadataItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RegionMetadataItem.


        :param name: The name of this RegionMetadataItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 120:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `120`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501
        if name is not None and not re.search(r'^.*\S.*$', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^.*\S.*$/`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this RegionMetadataItem.


        :return: The description of this RegionMetadataItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this RegionMetadataItem.


        :param description: The description of this RegionMetadataItem.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501
        if description is not None and len(description) > 300:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `300`")  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501
        if description is not None and not re.search(r'^.*\S.*$', description):  # noqa: E501
            raise ValueError("Invalid value for `description`, must be a follow pattern or equal to `/^.*\S.*$/`")  # noqa: E501

        self._description = description

    @property
    def display_order(self) -> int:
        """Gets the display_order of this RegionMetadataItem.


        :return: The display_order of this RegionMetadataItem.
        :rtype: int
        """
        return self._display_order

    @display_order.setter
    def display_order(self, display_order: int):
        """Sets the display_order of this RegionMetadataItem.


        :param display_order: The display_order of this RegionMetadataItem.
        :type display_order: int
        """
        if display_order is not None and display_order < 1:  # noqa: E501
            raise ValueError("Invalid value for `display_order`, must be a value greater than or equal to `1`")  # noqa: E501

        self._display_order = display_order

    @property
    def parent_code(self) -> str:
        """Gets the parent_code of this RegionMetadataItem.


        :return: The parent_code of this RegionMetadataItem.
        :rtype: str
        """
        return self._parent_code

    @parent_code.setter
    def parent_code(self, parent_code: str):
        """Sets the parent_code of this RegionMetadataItem.


        :param parent_code: The parent_code of this RegionMetadataItem.
        :type parent_code: str
        """
        if parent_code is not None and len(parent_code) > 40:
            raise ValueError("Invalid value for `parent_code`, length must be less than or equal to `40`")  # noqa: E501
        if parent_code is not None and len(parent_code) < 10:
            raise ValueError("Invalid value for `parent_code`, length must be greater than or equal to `10`")  # noqa: E501
        if parent_code is not None and not re.search(r'^[A-Z_]+$', parent_code):  # noqa: E501
            raise ValueError("Invalid value for `parent_code`, must be a follow pattern or equal to `/^[A-Z_]+$/`")  # noqa: E501

        self._parent_code = parent_code

    @property
    def aliases(self) -> List[str]:
        """Gets the aliases of this RegionMetadataItem.


        :return: The aliases of this RegionMetadataItem.
        :rtype: List[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases: List[str]):
        """Sets the aliases of this RegionMetadataItem.


        :param aliases: The aliases of this RegionMetadataItem.
        :type aliases: List[str]
        """
        if aliases is not None and len(aliases) > 20:
            raise ValueError("Invalid value for `aliases`, number of items must be less than or equal to `20`")  # noqa: E501
        if aliases is not None and len(aliases) < 0:
            raise ValueError("Invalid value for `aliases`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._aliases = aliases
