from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_models.models.base_model import Model
from openapi_models import util


class Region(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    EAST_ASIA_AND_PACIFIC = "EAST_ASIA_AND_PACIFIC"
    EUROPE_AND_CENTRAL_ASIA = "EUROPE_AND_CENTRAL_ASIA"
    LATIN_AMERICA_AND_CARIBBEAN = "LATIN_AMERICA_AND_CARIBBEAN"
    MIDDLE_EAST_AND_NORTH_AFRICA = "MIDDLE_EAST_AND_NORTH_AFRICA"
    NORTH_AMERICA = "NORTH_AMERICA"
    SOUTH_ASIA = "SOUTH_ASIA"
    SUB_SAHARAN_AFRICA = "SUB_SAHARAN_AFRICA"

    def __init__(self):  # noqa: E501
        """Region - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "Region":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Region of this Region.  # noqa: E501
        :rtype: Region
        """
        return util.deserialize_model(dikt, cls)
