# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Region(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    EAST_ASIA_AND_PACIFIC = "east_asia_and_pacific"
    EUROPE_AND_CENTRAL_ASIA = "europe_and_central_asia"
    LATIN_AMERICA_AND_CARIBBEAN = "latin_america_and_caribbean"
    MIDDLE_EAST_AND_NORTH_AFRICA = "middle_east_and_north_africa"
    NORTH_AMERICA = "north_america"
    SOUTH_ASIA = "south_asia"
    SUB_SAHARAN_AFRICA = "sub_saharan_africa"

    def __init__(self):  # noqa: E501
        """Region - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "Region":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Region of this Region.  # noqa: E501
        :rtype: Region
        """
        return util.deserialize_model(dikt, cls)
